# Generated by Django 3.2.3 on 2021-09-18 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emailinfo',
            fields=[
                ('index', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='索引')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('poster', models.CharField(max_length=20, verbose_name='发帖人')),
                ('recipient', models.CharField(max_length=20, verbose_name='收件人')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='是否匿名')),
                ('comment_num', models.IntegerField(default=0, verbose_name='评论数')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='帖子状态')),
                ('operator', models.CharField(max_length=10, verbose_name='操作人')),
            ],
            options={
                'verbose_name_plural': '邮件信息表',
                'db_table': 'emailinfo',
            },
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='工号')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('sex', models.CharField(max_length=2, verbose_name='性别')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('keshi', models.CharField(max_length=14, verbose_name='科室')),
                ('duty', models.CharField(max_length=10, verbose_name='职务')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_dean', models.BooleanField(default=False, verbose_name='是否院长')),
                ('is_active', models.BooleanField(default=True, verbose_name='账号状态')),
                ('ud_operator', models.CharField(max_length=10, verbose_name='操作人')),
            ],
            options={
                'verbose_name_plural': '用户信息',
                'db_table': 'userinfo',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('index', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='索引')),
                ('content', models.TextField(verbose_name='评论')),
                ('commentator', models.CharField(max_length=20, verbose_name='评论人')),
                ('floor', models.IntegerField(default=0, verbose_name='楼层')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='评论状态')),
                ('operator', models.CharField(max_length=10, verbose_name='操作人')),
                ('email_index', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailbx.emailinfo')),
            ],
            options={
                'verbose_name_plural': '评论表',
                'db_table': 'comments',
            },
        ),
    ]
