# Generated by Django 3.2.3 on 2021-12-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailbx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(default='', max_length=16, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='operator',
            field=models.CharField(default='', max_length=10, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='emailinfo',
            name='operator',
            field=models.CharField(default='', max_length=10, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='工号'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='ud_operator',
            field=models.CharField(default='', max_length=10, verbose_name='操作人'),
        ),
    ]
