# Generated by Django 3.2.3 on 2021-12-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailbx', '0002_auto_20211202_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='commentator_id',
            field=models.CharField(default='', max_length=12, verbose_name='评论人id'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
